name: CI

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ubuntu-20.04-gpu  # Use the GPU runner
    timeout-minutes: 60
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1.9'
        os:
          - ubuntu-20.04-gpu
        arch:
          - x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Install CUDA toolkit
        run: sudo apt-get update && sudo apt-get install -y nvidia-cuda-toolkit

      - name: Install Julia dependencies
        run: julia -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests
        uses: julia-actions/julia-runtest@v1
      
      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
